version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ANTHROPIC_API_KEY=your_api_key_here
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:all

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - app